name: 'Query Git branch name'
description: 'Get pure Git branch name without ref/ prefix'
branding:
  icon: 'git-branch'
  color: 'blue'
inputs:
  name:
    description: 'The environment variable name to export, ex. `CURRENT_BRANCH`, `GIT_BRANCH`'
    required: true
    default: 'GIT_BRANCH_NAME'
outputs:
  git_branch_name:
    description: 'The current Git branch name'
runs:
  using: 'node16'
  main: 'dist/index.js'
